spring:
  application:
    name: p2p-platform
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  r2dbc:
    pool:
      initial-size: 10
      max-size: 30
      max-idle-time: 30m
      validation-query: SELECT 1
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:p2p_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  redis:
    timeout: 10s
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: -1ms
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

security:
  jwt:
    secret: ${JWT_SECRET:your-secret-key-should-be-very-long-and-secure}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in milliseconds
    verification-expiration: ${JWT_VERIFICATION_EXPIRATION:3600000} # 1 hour in milliseconds
    reset-expiration: ${JWT_RESET_EXPIRATION:900000} # 15 minutes in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.p2p: ${LOG_LEVEL:INFO}
    org.springframework.web: INFO
    org.springframework.data.r2dbc: ${LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:logs/p2p-platform.log}
    max-size: 10MB
    max-history: 30

stripe:
  api-key: ${STRIPE_API_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  currency: HKD

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

app:
  upload:
    path: ${UPLOAD_PATH:uploads}
  cache:
    default-ttl: 3600
  notification:
    email:
      enabled: true
      from: noreply@p2p-platform.com
    push:
      enabled: true
  cleanup:
    notification-retention-days: 30
    chat-message-retention-days: 90

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true
  packages-to-scan: com.p2p.controller
